/* ============================================================
   plan.js — 训练计划数据源（唯一数据源）
   每个板块 15 个动作，按 subGroup 配额随机抽 6 个。
   muscle 字段 = 人体图高亮部位（f-=正面, b-=背面）
   img 字段   = 可选外部演示动图链接；留空则只显示肌肉发力图
   ============================================================ */

const MUSCLE_LABELS = {
  'f-chest': '胸大肌', 'f-delt': '三角肌前/中束', 'f-biceps': '肱二头肌',
  'f-forearm': '前臂', 'f-abs': '腹直肌', 'f-obliques': '腹斜肌', 'f-quads': '股四头肌',
  'b-delt': '三角肌后束', 'b-traps': '斜方肌', 'b-lats': '背阔肌', 'b-midback': '中背',
  'b-triceps': '肱三头肌', 'b-lowback': '下背', 'b-glute': '臀大肌',
  'b-glutemed': '臀中肌', 'b-hams': '腘绳肌', 'b-calves': '小腿'
};

const PLAN = {
  A: {
    key: 'A', title: '胸 · 肩', en: 'CHEST / SHOULDERS',
    note: '推力日 · 上肢塑形，求紧致线条不求大重量',
    quota: { chest: 3, shoulder: 3 }, // shoulder 含至少 1 个后束
    exercises: [
      { id:'a1', name:'平板杠铃卧推', sub:'胸-中胸', group:'chest', sets:4, reps:'12', rest:75,
        cues:['肩胛后缩下沉、挺胸', '杠铃落至乳头连线', '全程胸主导发力，肘约 75°'],
        mp:['f-chest'], ms:['f-delt','b-triceps'] },
      { id:'a2', name:'上斜哑铃卧推', sub:'胸-上胸', group:'chest', sets:3, reps:'12', rest:60,
        cues:['椅背 30-45°', '哑铃沿弧线推起、顶峰收紧', '肩胛稳定不耸肩'],
        mp:['f-chest'], ms:['f-delt'] },
      { id:'a3', name:'平板哑铃卧推', sub:'胸-中胸', group:'chest', sets:3, reps:'12', rest:60,
        cues:['底部充分拉伸胸肌', '手腕中立、肘下沉', '顶部不锁死、保持张力'],
        mp:['f-chest'], ms:['b-triceps'] },
      { id:'a4', name:'蝴蝶机夹胸', sub:'胸-内侧', group:'chest', sets:3, reps:'15', rest:45,
        cues:['想象抱大树画弧', '顶峰挤压胸肌 1 秒', '离心慢放感受拉伸'],
        mp:['f-chest'], ms:[] },
      { id:'a5', name:'上斜绳索夹胸', sub:'胸-上胸', group:'chest', sets:3, reps:'15', rest:45,
        cues:['身体微前倾', '双手由下往上交汇', '顶峰停顿挤压上胸'],
        mp:['f-chest'], ms:['f-delt'] },
      { id:'a6', name:'跪姿俯卧撑', sub:'胸-中胸', group:'chest', sets:3, reps:'力竭', rest:45,
        cues:['膝着地、身体成直线', '下放至胸贴近地面', '核心收紧不塌腰'],
        mp:['f-chest'], ms:['f-delt','b-triceps'] },
      { id:'a7', name:'高位绳索夹胸', sub:'胸-下胸', group:'chest', sets:3, reps:'15', rest:45,
        cues:['滑轮置高位、由上往下', '双手交汇于髋前', '挤压下胸'],
        mp:['f-chest'], ms:[] },
      { id:'a8', name:'坐姿哑铃肩上推举', sub:'肩-前/中束', group:'shoulder', sets:4, reps:'12', rest:75,
        cues:['坐稳靠背、核心收紧', '推至接近锁死、不耸肩', '下放至耳侧高度'],
        mp:['f-delt'], ms:['b-triceps'] },
      { id:'a9', name:'阿诺德推举', sub:'肩-前/中束', group:'shoulder', sets:3, reps:'12', rest:60,
        cues:['起始掌心朝己', '上推同时旋转至掌心朝前', '动作流畅控制'],
        mp:['f-delt'], ms:[] },
      { id:'a10', name:'哑铃侧平举', sub:'肩-中束', group:'shoulder', sets:4, reps:'15', rest:45,
        cues:['微屈肘、小拇指略高', '肩为轴抬至与肩平', '不借力、慢放控制'],
        mp:['f-delt'], ms:[] },
      { id:'a11', name:'绳索侧平举', sub:'肩-中束', group:'shoulder', sets:3, reps:'15', rest:45,
        cues:['绳索置低位、单侧', '全程持续张力', '上身保持稳定'],
        mp:['f-delt'], ms:[] },
      { id:'a12', name:'俯身哑铃飞鸟', sub:'肩-后束', group:'shoulder', rear:true, sets:3, reps:'15', rest:45,
        cues:['俯身约 90°、背挺直', '微屈肘向两侧展开', '挤压后束、不耸肩'],
        mp:['b-delt'], ms:['b-traps'] },
      { id:'a13', name:'绳索面拉', sub:'肩-后束', group:'shoulder', rear:true, sets:3, reps:'15', rest:45,
        cues:['绳索拉向面部、肘高于手', '外旋打开、挤压后束', '改善圆肩'],
        mp:['b-delt'], ms:['b-traps'] },
      { id:'a14', name:'反向蝴蝶机', sub:'肩-后束', group:'shoulder', rear:true, sets:3, reps:'15', rest:45,
        cues:['胸贴靠垫', '微屈肘向后展开', '顶峰挤压、慢放'],
        mp:['b-delt'], ms:[] },
      { id:'a15', name:'站姿哑铃前平举', sub:'肩-前束', group:'shoulder', sets:3, reps:'12', rest:45,
        cues:['交替或同时抬至与肩平', '不晃身借力', '控制离心'],
        mp:['f-delt'], ms:[] },
    ]
  },
  B: {
    key: 'B', title: '背 · 核心 · 手臂', en: 'BACK / CORE / ARMS',
    note: '拉力日 · 改善体态，强化核心稳定',
    quota: { back: 2, biceps: 1, triceps: 1, core: 2 },
    exercises: [
      { id:'b1', name:'高位下拉', sub:'背-背阔', group:'back', sets:4, reps:'12', rest:75,
        cues:['宽握、肩胛下沉', '拉至锁骨上沿', '想象用肘往下拉'],
        mp:['b-lats'], ms:['f-biceps'] },
      { id:'b2', name:'坐姿绳索划船', sub:'背-中背', group:'back', sets:4, reps:'12', rest:75,
        cues:['挺胸、背挺直', '拉至腹部、挤压肩胛', '不后仰借力'],
        mp:['b-midback'], ms:['b-lats','f-biceps'] },
      { id:'b3', name:'单臂哑铃划船', sub:'背-背阔/中背', group:'back', sets:3, reps:'12', rest:60,
        cues:['一手撑凳、背平', '哑铃沿体侧上拉至髋', '顶峰挤压、慢放'],
        mp:['b-lats'], ms:['b-midback'] },
      { id:'b4', name:'杠铃俯身划船', sub:'背-中背', group:'back', sets:3, reps:'12', rest:75,
        cues:['屈髋俯身约 45°、背挺直', '杠铃拉向下腹', '核心收紧护腰'],
        mp:['b-midback'], ms:['b-lats'] },
      { id:'b5', name:'直臂下压', sub:'背-背阔', group:'back', sets:3, reps:'15', rest:45,
        cues:['直臂、以背阔下压', '杆下压至大腿前', '感受背阔收缩'],
        mp:['b-lats'], ms:[] },
      { id:'b6', name:'哑铃交替弯举', sub:'肱二头肌', group:'biceps', sets:3, reps:'12', rest:45,
        cues:['大臂贴体侧不动', '弯举至顶峰收紧', '慢放至完全伸展'],
        mp:['f-biceps'], ms:[] },
      { id:'b7', name:'杠铃弯举', sub:'肱二头肌', group:'biceps', sets:3, reps:'12', rest:45,
        cues:['肘固定、不晃身', '全程控制、不甩', '顶峰挤压'],
        mp:['f-biceps'], ms:[] },
      { id:'b8', name:'锤式弯举', sub:'肱二头肌-肱肌', group:'biceps', sets:3, reps:'12', rest:45,
        cues:['掌心相对（中立握）', '大臂固定', '兼顾前臂'],
        mp:['f-biceps'], ms:['f-forearm'] },
      { id:'b9', name:'绳索下压', sub:'肱三头肌', group:'triceps', sets:3, reps:'15', rest:45,
        cues:['大臂夹紧体侧', '下压至完全伸直', '顶峰挤压三头'],
        mp:['b-triceps'], ms:[] },
      { id:'b10', name:'仰卧臂屈伸', sub:'肱三头肌', group:'triceps', sets:3, reps:'12', rest:45,
        cues:['大臂垂直、肘固定', '下放至额头上方', '仅小臂活动'],
        mp:['b-triceps'], ms:[] },
      { id:'b11', name:'窄距跪姿俯卧撑', sub:'肱三头肌', group:'triceps', sets:3, reps:'力竭', rest:45,
        cues:['双手与肩同宽偏窄', '肘贴体侧下放', '三头主导推起'],
        mp:['b-triceps'], ms:['f-chest'] },
      { id:'b12', name:'悬垂/屈膝举腿', sub:'核心-下腹', group:'core', sets:3, reps:'15', rest:45,
        cues:['卷骨盆、下腹发力', '不靠惯性摆动', '慢放控制'],
        mp:['f-abs'], ms:[] },
      { id:'b13', name:'平板支撑', sub:'核心-整体', group:'core', sets:3, reps:'45秒', rest:45,
        cues:['肘肩垂直、身体成直线', '收紧腹臀、不塌腰', '均匀呼吸'],
        mp:['f-abs'], ms:['f-obliques'] },
      { id:'b14', name:'俄罗斯转体', sub:'核心-腹斜肌', group:'core', sets:3, reps:'20', rest:45,
        cues:['坐姿后仰、抬脚', '左右转体触地', '以腰腹带动'],
        mp:['f-obliques'], ms:['f-abs'] },
      { id:'b15', name:'卷腹', sub:'核心-上腹', group:'core', sets:3, reps:'20', rest:45,
        cues:['下背贴地、卷起肩胛', '呼气收紧上腹', '不抱头拉脖子'],
        mp:['f-abs'], ms:[] },
    ]
  },
  C: {
    key: 'C', title: '上臀 · 腿', en: 'GLUTES / LEGS',
    note: '提臀日 · 全程髋主导，重臀线 · 控腿围（避开大重量股四头主导）',
    quota: { 'glute-hip': 3, 'glute-single': 1, 'glute-med': 2 },
    exercises: [
      { id:'c1', name:'杠铃臀冲', sub:'臀大肌', group:'glute-hip', sets:4, reps:'12', rest:75,
        cues:['上背靠凳、收下巴', '顶峰夹紧臀、髋充分伸展', '不靠腰过度后仰'],
        mp:['b-glute'], ms:['b-hams'] },
      { id:'c2', name:'双腿臀桥', sub:'臀大肌', group:'glute-hip', sets:3, reps:'15', rest:60,
        cues:['脚跟发力顶髋', '顶峰夹臀停 1 秒', '臀主导、非腰'],
        mp:['b-glute'], ms:[] },
      { id:'c3', name:'罗马尼亚硬拉', sub:'臀大肌·腘绳肌', group:'glute-hip', sets:3, reps:'12', rest:75,
        cues:['屈髋向后送、腿微屈', '杠/铃贴腿下滑至膝下', '感受腘绳臀拉伸后起身'],
        mp:['b-glute','b-hams'], ms:['b-lowback'] },
      { id:'c4', name:'直腿硬拉', sub:'臀大肌·腘绳肌', group:'glute-hip', sets:3, reps:'12', rest:75,
        cues:['腿接近伸直、屈髋', '背挺直不弓背', '臀腘发力起身'],
        mp:['b-hams','b-glute'], ms:['b-lowback'] },
      { id:'c5', name:'山羊挺身（背屈伸）', sub:'臀大肌·腘绳肌', group:'glute-hip', sets:3, reps:'15', rest:60,
        cues:['髋垫卡髋部', '臀腘发力抬起至身体成直线', '不过度后伸腰'],
        mp:['b-glute','b-lowback'], ms:['b-hams'] },
      { id:'c6', name:'单腿臀桥', sub:'臀大肌·稳定', group:'glute-single', sets:3, reps:'12/侧', rest:60,
        cues:['单脚跟撑地顶髋', '骨盆保持水平', '顶峰夹臀'],
        mp:['b-glute'], ms:[] },
      { id:'c7', name:'后撤步弓步', sub:'单腿-臀大肌', group:'glute-single', sets:3, reps:'12/侧', rest:60,
        cues:['后撤下蹲、重心在前脚跟', '前脚跟蹬地起身', '上身略前倾促臀发力'],
        mp:['b-glute'], ms:['b-hams'] },
      { id:'c8', name:'保加利亚分腿蹲（前倾臀主导）', sub:'单腿-臀大肌', group:'glute-single', sets:3, reps:'12/侧', rest:60,
        cues:['后脚搭凳、上身前倾', '下蹲至前大腿平行', '前脚跟发力、臀主导'],
        mp:['b-glute'], ms:['b-hams'] },
      { id:'c9', name:'绳索后踢腿', sub:'臀大肌上部', group:'glute-single', sets:3, reps:'15/侧', rest:45,
        cues:['踝带固定、微前倾', '后伸髋、夹臀上部', '不甩、慢放'],
        mp:['b-glute'], ms:[] },
      { id:'c10', name:'跪姿驴踢', sub:'臀大肌上部', group:'glute-single', sets:3, reps:'15/侧', rest:45,
        cues:['四点跪姿、背平', '屈膝向上踢、脚底朝天', '顶峰夹臀、不塌腰'],
        mp:['b-glute'], ms:[] },
      { id:'c11', name:'弹力带侧向行走', sub:'臀中肌', group:'glute-med', sets:3, reps:'20步', rest:45,
        cues:['带套膝/踝、半蹲', '侧向迈步保持张力', '膝盖外撑不内扣'],
        mp:['b-glutemed'], ms:[] },
      { id:'c12', name:'站姿绳索髋外展', sub:'臀中肌', group:'glute-med', sets:3, reps:'15/侧', rest:45,
        cues:['踝带固定、站稳', '腿向外侧抬起', '上身不晃、控制'],
        mp:['b-glutemed'], ms:[] },
      { id:'c13', name:'蚌式开合', sub:'臀中肌', group:'glute-med', sets:3, reps:'20/侧', rest:45,
        cues:['侧卧屈膝、脚并拢', '上膝向外打开如蚌壳', '骨盆不后翻'],
        mp:['b-glutemed'], ms:[] },
      { id:'c14', name:'坐姿髋外展机', sub:'臀中肌', group:'glute-med', sets:3, reps:'20', rest:45,
        cues:['上身微前倾', '双膝向外撑开', '顶峰挤压臀中肌'],
        mp:['b-glutemed'], ms:[] },
      { id:'c15', name:'弹力带臀桥外展', sub:'臀大肌·臀中肌', group:'glute-med', sets:3, reps:'15', rest:45,
        cues:['臀桥顶位带膝外展', '同时夹臀+外撑', '复合刺激臀线'],
        mp:['b-glute','b-glutemed'], ms:[] },
    ]
  }
};

/* 三练循环顺序：A → B → C → A ... */
const CYCLE = ['A', 'B', 'C'];
